# Generated by Django 5.0.6 on 2024-09-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_questions_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
    ]
