# Generated by Django 5.0.6 on 2024-09-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('img', models.FileField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('title', models.CharField(max_length=150)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.episodes')),
            ],
        ),
    ]
